config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'about#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#register'
  get '/register', to: 'users#register'
  get '/register_twitter', to: 'users#register_twitter'
  delete '/users/logout', to: 'users#logout'
  resources :users, except: [:new]

  # Callbacks
  get '/twitter_callback', to: 'callbacks#twitter_callback'

  # TweetViews
  post '/tweet_views', to: 'tweet_views#create'
  get '/tweet_views', to: 'tweet_views#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oauth.rb
class Oauth < ApplicationRecord
  belongs_to :user
end

app/models/tweet_view.rb
class TweetView < ApplicationRecord
  belongs_to :user

  def self.reset_counts
    TweetView.update_all count: 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, length: {maximum: 1000}, uniqueness: true
  
  has_one :tweet_view
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    @current_user ||= Oauth.find_by(oauth_token: session[:oauth_token])&.user
  end

  def authenticate_user
    unless session[:oauth_token].present? && session[:oauth_token_secret].present?
      flash[:error] = 'You must be logged in to access this section'
      redirect_to register_path
    end
  end
end

app/controllers/callbacks_controller.rb
require_relative '../../gems/twitter/lib/twitter'

class CallbacksController < ApplicationController
  def twitter_callback
    logger.info('Starting twitter callback')
    local = ENV["RAILS_ENV"] == "production" ? false : true

    twitter_client = Twitter::Client.new(consumer_secret: ENV['TWITTER_CONSUMER_SECRET'],
                                         consumer_key: ENV['TWITTER_CONSUMER_KEY'], local: local)
    body = twitter_client.get_access_token(oauth_verifier: params[:oauth_verifier], oauth_token: params[:oauth_token])
    puts "GET ACCESS TOKEN #{body}"
    oauth_token, oauth_token_secret, user_id, screen_name = twitter_client.extract_access_token_params(body: body)
    puts "EXTRACT ACCESS: #{oauth_token}, #{oauth_token_secret}, #{user_id}, #{screen_name}"

    user = User.find_by(username: screen_name)
    if user.nil?
      logger.info('Creating a new user')
      user = User.create!(username: screen_name)
      Oauth.create!(oauth_token: oauth_token, oauth_token_secret: oauth_token_secret, oauth_user_id: user_id, screen_name: screen_name, user_id: user.id)
    else
      logger.info('User already exists so updating Oauth')
      old_oauth = Oauth.find_by(user_id: user.id)
      old_oauth.update!(oauth_token: oauth_token, oauth_token_secret: oauth_token_secret)
    end

    session[:oauth_token] = oauth_token
    session[:oauth_token_secret] = oauth_token_secret
    redirect_to user
  rescue StandardError => e
    logger.error("Error in twitter_callback: #{e}")
  end
end

app/controllers/tweet_views_controller.rb
require_relative '../../gems/twitter/lib/twitter'

class TweetViewsController < ApplicationController
  before_action :authenticate_user

  def create
    user = User.find(params[:user_id])
    tweet_view = user.tweet_view

    if tweet_view&.count && tweet_view&.count > 19
      render :error
      return
    end

    if tweet_view.nil?
      logger.info 'A tweet view for this user does not already exist, creating one now'
      tweet_view = TweetView.create(user_id: user.id, count: 0)
    end

    tweet_view.increment!(:count)
    local = ENV['RAILS_ENV'] == 'production' ? false : true

    twitter_client = Twitter::Client.new(local: local)
    tweet = twitter_client.fetch_tweet(tweet_id: params[:tweet_id], bearer_token: ENV['TWITTER_BEARER_TOKEN'])
    if tweet.has_key?('data') && tweet['data'].present?
      @tweet_content = tweet['data']['text']
      @tweet_user = params[:tweet_user]
    else
      raise StandardError.new 'The response did not contain a "data" key.'
    end

    if tweet['includes']
      if tweet['includes']['media'].any?
        @tweet_image_url = tweet['includes']['media'][0]['url']
      end
    end
  rescue ActiveRecord::RecordNotFound => e
    flash[:error] = 'User not found'
    redirect_to register_path
  rescue StandardError => e
    flash.now[:error] = 'There was an unexpected error'
    logger.error("There was an unexpected error in show: #{e}")
  end
end

app/controllers/users_controller.rb
require_relative '../../gems/twitter/lib/twitter'

class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show]

  def register_twitter
    logger.info('Starting register_twitter')
    local = ENV["RAILS_ENV"] == "production" ? false : true

    twitter_client = Twitter::Client.new(consumer_secret: ENV['TWITTER_CONSUMER_SECRET'],
                                         consumer_key: ENV['TWITTER_CONSUMER_KEY'], local: local)
    oauth_token = twitter_client.get_oauth_token
    puts "OAUTH TOKEN #{oauth_token}"
    redirect_url = twitter_client.generate_redirect_url(oauth_token: oauth_token)
    puts "REDIRECT URL: #{redirect_url}"
    logger.info('Redirecting to twitter for authorization')
    redirect_to redirect_url
  rescue StandardError => e
    logger.error("Error in register_twitter #{e}")
  end

  def show
    @user = User.find(params[:id])
    local = ENV["RAILS_ENV"] == "production" ? false : true
    twitter_client = Twitter::Client.new(oauth_token: session[:oauth_token], oauth_token_secret: session[:oauth_token_secret], local: local)
    @timeline = twitter_client.fetch_timeline

  rescue ActiveRecord::RecordNotFound => e
    flash[:error] = 'User not found'
    redirect_to register_path
  rescue Twitter::RateLimitExceeded => e
    flash.now[:error] = 'Rate limit exceeded. Please wait 15 minutes before requesting more tweets.'
  rescue StandardError => e
    flash[:error] = 'There was an unexpected error'
    logger.error("There was an unexpected error in show: #{e}")
  end

  def logout
    session.destroy
    redirect_to root_path
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_views_helper.rb
module TweetViewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<p class="pl-6 pt-4">Moditter is an app that helps you moderate your twitter usage. You are allowed to view 20 tweets per day. Before viewing a tweet you can see who the author is.</p>

<p class="pl-6 pt-2">We only require read access to your twitter account and we do not store your email or any other personal information.</p>
<% if session[:oauth_token].blank? %>
  <p class="pl-6 pt-6">Sign in to your twitter account to get started.</p>
  <div class="pl-6 pt-2">
    <%= link_to image_tag('twitter.png', border: 0), register_twitter_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moditter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav class="bg-blue-300 h-13 w-screen p-6 flex justify-left items-center">
      <h3 class="mr-6 text-xl">MODITTER</h3>
      <% if session[:oauth_token].present? %>
        <%= link_to "Timeline", @current_user, class: 'mr-4' %>
      <% else %>
        <%= link_to "Home", root_path, class: "mr-4 text-blue" %>
      <% end %>
      <%= link_to "About", '/about', class: "mr-4" %>
      <% if session[:oauth_token].present? %>
        <%= link_to "Logout", users_logout_path, method: :delete, class: 'mr-4' %>
      <% end %>
    </nav>

    <% if flash.any? %>
      <%= flash.each do |type, msg| %>
        <div class="<%= type %>">
          <%= msg %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tweet_views/create.html.erb
<%= turbo_frame_tag "tweet" do %>
  <p><%= @tweet_content %></p>
  <% if @tweet_image_url.present? %>
    <img src=<%= @tweet_image_url %> />
  <% end %>
  <span><%= "@" + @tweet_user %></span>
<% end %>

app/views/tweet_views/error.html.erb
<%= turbo_frame_tag "tweet" do %>
    <h3>You've already viewed 20 tweets for the day. Come back tomorrow for more!</h3>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mt-3 border-2 border-solid border-blue-300 w-full p-4">
  <%= turbo_frame_tag "tweet" do %>
    <% if tweet.present? && tweet.is_a?(Hash) %>
      <p class="font-bold mt-2 mb-2"><%= tweet['user']['screen_name'] %></p>
      <%= form_with url: tweet_views_path do |f| %>
        <%= f.hidden_field(:user_id, value: user.id) %>
        <%= f.hidden_field(:tweet_user, value: tweet['user']['screen_name']) %>
        <%= f.hidden_field(:tweet_id, value: tweet['id']) %>
        <%= f.submit "Show this Tweet!", class: "bg-blue-500 p-2 rounded-lg text-white cursor-pointer text-md" %>
      <% end %>
    <% end %>
  <% end%>
</div>

app/views/users/register.html.erb
<div class="register-form-container mt-6">
  <h1 class="text-3xl mb-6">Moderate your twitter usage.</h1>
  <%= link_to image_tag('twitter.png', border: 0), register_twitter_path %>
</div>

app/views/users/show.html.erb
<div class="tweets-container">
  <h1 class="mt-2 mb-2 font-bold text-lg">Welcome To Moditter <%= @user&.username%>!</h1>
  <% if !@timeline.nil? && @timeline.any? %>
      <% @timeline.each do |t| %>
          <%= render "tweets/tweet", tweet: t, user: @user %>
      <% end %>
  <% end %>
</div>